spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doorserve
    username: akshit_kharbanda
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${process.env.GOOGLE_CLIENT_ID}
            client-secret: ${process.env.GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  secret-key: ${JWT_SECRET:process.env.JWT_SECRET}
  expiration: 86400000 # 24 hours

server:
  port: 8080
