spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doorserve
    username: ${PSQL_USERNAME}
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - openid
              - profile
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.oauth2: DEBUG

jwt:
  secret-key: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

server:
  port: 8080
